# Cloud Run 無料枠最適化設定
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: youtube-chat-monitor
  annotations:
    # Cloud Run固有のアノテーション
    run.googleapis.com/cpu-throttling: "true"  # CPU only during request (デフォルト)
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # リソース制限設定（無料枠最適化）
        run.googleapis.com/cpu: "0.167"        # 最小CPU（256Mi RAMに対応）
        run.googleapis.com/memory: "256Mi"     # 最小メモリ
        run.googleapis.com/startup-cpu-boost: "true"  # コールドスタート高速化
        
        # 同期実行設定（SSE用）
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/timeout: "3600s"   # 60分（SSE最大接続時間）
        
        # オートスケーリング設定
        autoscaling.knative.dev/maxScale: "10"  # 最大10インスタンス
        autoscaling.knative.dev/minScale: "0"   # 完全scale-to-zero（コスト削減）
        
        # 並行実行数制限（SSE接続特性考慮）
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/max-instance-request-concurrency: "1"  # 1リクエスト/インスタンス
        
    spec:
      # サービスアカウント（必要に応じて設定）
      # serviceAccountName: youtube-chat-monitor-sa
      
      containers:
      - name: youtube-chat-monitor
        image: gcr.io/PROJECT_ID/youtube-chat-monitor:latest
        
        # ポート設定
        ports:
        - name: http1
          containerPort: 8080
          
        # 環境変数
        env:
        - name: PORT
          value: "8080"
        - name: MAX_CHAT_MESSAGES
          value: "500"     # 無料枠向け削減
        - name: MAX_USERS  
          value: "100"     # 無料枠向け削減
        - name: LOG_LEVEL
          value: "WARN"    # ログ量削減
        - name: YT_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-secret
              key: api-key
              
        # リソース制限
        resources:
          limits:
            cpu: "0.167"
            memory: "256Mi"
          requests:
            cpu: "0.083"   # 最小リクエスト値
            memory: "128Mi"
            
        # ヘルスチェック設定
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
          
        # セキュリティ設定
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534  # nobody user
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

---
# Secret設定例（別途適用が必要）
apiVersion: v1
kind: Secret
metadata:
  name: youtube-api-secret
type: Opaque
stringData:
  api-key: "YOUR_YOUTUBE_API_KEY_HERE"