name: CI

on:
  push:
    branches: [ main, feat/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
      - name: Test
        run: npm run test -- --run

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test
        run: go test ./...
